export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";

export const FETCH_COMMENTS_REPLIES = "FETCH_COMMENTS_REPLIES";
export const FETCH_COMMENTS_REPLIES_SUCCESS = "FETCH_COMMENTS_REPLIES_SUCCESS";
export const FETCH_COMMENTS_REPLIES_ERROR = "FETCH_COMMENTS_REPLIES_ERROR";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";
