export const CREATE_MOVIE = "CREATE_MOVIE";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR";

export const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_ERROR = "FETCH_ALL_MOVIES_ERROR";

export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";

export const LIKE_MOVIE = "LIKE_MOVIE";
export const LIKE_MOVIE_SUCCESS = "LIKE_MOVIE_SUCCESS";
export const LIKE_MOVIE_ERROR = "LIKE_MOVIE_ERROR";

export const DISLIKE_MOVIE = "DISLIKE_MOVIE";
export const DISLIKE_MOVIE_SUCCESS = "DISLIKE_MOVIE_SUCCESS";
export const DISLIKE_MOVIE_ERROR = "DISLIKE_MOVIE_ERROR";
