export const CREATE_MOVIE = "CREATE_MOVIE";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR";

export const FETCH_ALL_MOVIES = "FETCH_ALL_MOVIES";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_ERROR = "FETCH_ALL_MOVIES_ERROR";

export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";

export const LIKE_MOVIE = "LIKE_MOVIE";
export const LIKE_MOVIE_SUCCESS = "LIKE_MOVIE_SUCCESS";
export const LIKE_MOVIE_ERROR = "LIKE_MOVIE_ERROR";

export const DISLIKE_MOVIE = "DISLIKE_MOVIE";
export const DISLIKE_MOVIE_SUCCESS = "DISLIKE_MOVIE_SUCCESS";
export const DISLIKE_MOVIE_ERROR = "DISLIKE_MOVIE_ERROR";

export const FETCH_WATCHLIST = "FETCH_WATCHLIST";
export const FETCH_WATCHLIST_SUCCESS = "FETCH_WATCHLIST_SUCCESS";
export const FETCH_WATCHLIST_ERROR = "FETCH_WATCHLIST_ERROR";

export const TOGGLE_WATCHED = "TOGGLE_WATCHED";
export const TOGGLE_WATCHED_SUCCESS = "TOGGLE_WATCHED_SUCCESS";
export const TOGGLE_WATCHED_ERROR = "TOGGLE_WATCHED_ERROR";

export const TOGGLE_WATCHLIST = "TOGGLE_WATCHLIST";
export const TOGGLE_WATCHLIST_SUCCESS = "TOGGLE_WATCHLIST_SUCCESS";
export const TOGGLE_WATCHLIST_ERROR = "TOGGLE_WATCHLIST_ERROR";

export const DELETE_FROM_WATCHLIST = "DELETE_FROM_WATCHLIST";
export const DELETE_FROM_WATCHLIST_SUCCESS = "DELETE_FROM_WATCHLIST_SUCCESS";
export const DELETE_FROM_WATCHLIST_ERROR = "DELETE_FROM_WATCHLIST_ERROR";

export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_POPULAR_MOVIES_SUCCESS = "FETCH_POPULAR_MOVIES_SUCCESS";
export const FETCH_POPULAR_MOVIES_ERROR = "FETCH_POPULAR_MOVIES_ERROR";

export const FETCH_RELATED_MOVIES = "FETCH_RELATED_MOVIES";
export const FETCH_RELATED_MOVIES_SUCCESS = "FETCH_RELATED_MOVIES_SUCCESS";
export const FETCH_RELATED_MOVIES_ERROR = "FETCH_RELATED_MOVIES_ERROR";

export const FETCH_MOVIE_FROM_OMDB = "FETCH_MOVIE_FROM_OMDB";
export const FETCH_MOVIE_FROM_OMDB_SUCCESS = "FETCH_MOVIE_FROM_OMDB_SUCCESS";
export const FETCH_MOVIE_FROM_OMDB_ERROR = "FETCH_MOVIE_FROM_OMDB_ERROR";

export const ELASTIC_SEARCH = "ELASTIC_SEARCH";
export const ELASTIC_SEARCH_SUCCESS = "ELASTIC_SEARCH_SUCCESS";
export const ELASTIC_SEARCH_ERROR = "ELASTIC_SEARCH_ERROR";
